CREATE OR REPLACE PACKAGE UTILITY_PACK IS

  -- Author  : FZHANG
  -- Created : 12/8/2016 16:53:45 16:53:45 
  -- Purpose : miscellaneous utilities


  --get_hash_val returns a hashed string for any input string
  
  FUNCTION GET_HASH_VAL(P_IN_VAL IN VARCHAR2) RETURN VARCHAR2;

END UTILITY_PACK;
/
CREATE OR REPLACE PACKAGE BODY UTILITY_PACK IS

  FUNCTION GET_HASH_VAL(P_IN_VAL IN VARCHAR2) RETURN VARCHAR2 IS
    C_HASH_ARGORITHM CONSTANT PLS_INTEGER := DBMS_CRYPTO.HASH_SH1;
    C_CHARACTER      CONSTANT VARCHAR2(10) := 'AL32UTF8';
  
    L_HASH_VAL RAW(4000);
    L_IN       RAW(4000);
    L_RET      VARCHAR2(4000);
  BEGIN
  
    L_IN       := UTL_I18N.STRING_TO_RAW(P_IN_VAL, C_CHARACTER);
    L_HASH_VAL := DBMS_CRYPTO.HASH(SRC => L_IN, TYP => C_HASH_ARGORITHM);
    L_RET      := RAWTOHEX(L_HASH_VAL);
    RETURN L_RET;
  END GET_HASH_VAL;

END UTILITY_PACK;
/
